export enum TipoExpresion {
    PRIMITIVO,
    ARMITEMETICO,
    RELACIONAL,
    LOGICO,
    ACCESO_ID,
    FUNCION_NATIVA,
    INC_DEC,
    RETORNAR,
    CASTEO,
    TERNARIO,
    ACCESO,
    VECTOR_LITERAL
}